import curses

#Colours
BLACK = curses.COLOR_BLACK
WHITE = curses.COLOR_WHITE
RED = curses.COLOR_RED
YELLOW = curses.COLOR_YELLOW
GREEN = curses.COLOR_GREEN
CYAN = curses.COLOR_CYAN
BLUE = curses.COLOR_BLUE
MAGENTA = curses.COLOR_MAGENTA

#Terminal drawing characters

DOUBLE_TL_CORNER = "╔"
DOUBLE_TR_CORNER = "╗"
DOUBLE_BL_CORNER = "╚"
DOUBLE_BR_CORNER = "╝"
DOUBLE_HORIZ = "═"
DOUBLE_VERT = "║"
DOUBLE_HORIZ_TRUNC_RIGHT = "╞"
DOUBLE_HORIZ_TRUNC_LEFT = "╡"